# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b9de68e58f050164c948d5f9cd71a11dd950bc49740c84e203ada5fb5845ff6c39baaebaeb384d67963617cc69ad5169182508a82591ef8f394a8cec5d62549

test:
  secret_key_base: 5d7cb941eb232dcb17564fd6c9707538f660d98ea4186ce9611e5ea7ad44ee474165bb84810871ec93e9233574db91ea8d26e9c59e61a81323db745f10aa4f23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
